# Generated by Django 4.2.6 on 2023-10-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
    ]
